spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            server:
                webflux:
                    routes:
                        - id: zone-management-service
                          uri: lb://zone-management-service
                          predicates:
                              - Path=/zone-management-service/**

                        - id: sensor-telemetry-service
                          uri: lb://sensor-telemetry-service
                          predicates:
                            - Path=/sensor-telemetry-service/**
                          filters:
                            - name: UserIdHeaderFilter

                        - id: automation-control-service
                          uri: http://localhost:3000
                          predicates:
                              - Path=/automation-control-service/**

                        - id: crop-inventory-service
                          uri: http://localhost:3000
                          predicates:
                              - Path=/crop-inventory-service/**
    security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: https://external-issuer.example.com/.well-known/jwks.json


server:
    port: 8080

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/