spring.application.name=automation-control-service
server.port=8083
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
server.servlet.context-path=/automation-control-service

eureka.instance.hostname=