spring.application.name=sensor-telemetry-service
server.port=8082
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
server.servlet.context-path=/sensor-telemetry-service

spring.data.mongodb.uri=mongodb://localhost:27017/agms_sensor_db

